# If `true`, revaultd will start as a daemon. If you're using revaultd with revault-gui, you might want to keep it to `true`, so that the gui can start revaultd on its own. If you're starting `revaultd` for the first time, you may want to change it to `false`, so that you can see if something goes wrong.
daemon = true
log_level = "debug"
# The directory where all your revault data will be saved
data_dir = "/path/to/your/datadir/revault"

coordinator_host = "127.0.0.1:8383"
coordinator_noise_key = "f35b02f12ff3d64f3c7982b88ffb66fec37bce5796374a7be9e8e2dd9abbb558"

# The specifications of the Bitcoin Script that we are going to be tracking onchain, put here your own that you can
# generate with the `mscompiler` tool (in `contrib/tools`).
# These MUST NOT be changed after running revaultd for the first time, or you'll have to re-generate the database.
# If you have to change it, be sure to remove the previous db at `/path/to/your/data_dir/network/revaultd.sqlite3`.
[scripts_config]
deposit_descriptor = "wsh(multi(4,tpubDDcdMK347DzJfWk9a8uLuskgoSKTUPn1GtMYz91Q1WdptaY14BTF4KUFiQ3cq5K6ji4bgALTEy6HUuf3TULS4f98wYpaYLcAbym33g4hsPY/*,tpubDFUyR1hbbP14sGZ2St39RgJ9wUk4enPVYahtA5nPwPPWsGUNVFZt2ujRLShf4JqFXbJQLrgvFTodtXCWEnYQqUnMYzLaAWjuXsZnQTYZS5C/*,tpubDDHWtTfxQzAaYPvXmbVtfbKzkttwHqdE9pYsqcS4rgYxNWk2QAfmBMRkvkHDUBX96L4rw1PYxxgcQQ3rhns6EQdDbiGNi32UVXtwNWE7MsQ/*,tpubDEjfbTUpCPyZ3rUkxFPeScbMJUvijAJxanr5rPUy9Ah2HikqsxbaXSA6kjsXjUEBMe2Q5pKWicXWMUXjau7Am3W1fXHZPbrAMNXa7Z7ygEW/*))#hrdphuwc"
unvault_descriptor = "wsh(andor(multi(2,tpubDCvsodKgyz8apUfySTojc8WU6UPDXmv32Ct9hZqWGE7a6FcWpHoJ3Efa9zUqLWHX6PHthHXQehG1mrFtFVXNMcwt6kGwCuYk6adMDreyVGu/*,tpubDEBMdKAsdbmZsUUohCJjRCJ8NDxH4LJr79WSEE3bzHZGEoh7doFizgHhMQJKTN1SPnW44xspcb3f3Vav8JAthd3qGzTbq7zR12CFRkLvzG2/*),and_v(v:multi(4,030f64b922aee2fd597f104bc6cb3b670f1ca2c6c49b1071a1a6c010575d94fe5a,02abe475b199ec3d62fa576faee16a334fdb86ffb26dce75becebaaedf328ac3fe,0314f3dc33595b0d016bb522f6fe3a67680723d842c1b9b8ae6b59fdd8ab5cccb4,025eba3305bd3c829e4e1551aac7358e4178832c739e4fc4729effe428de0398ab),older(18)),thresh(4,pkh(tpubDDcdMK347DzJfWk9a8uLuskgoSKTUPn1GtMYz91Q1WdptaY14BTF4KUFiQ3cq5K6ji4bgALTEy6HUuf3TULS4f98wYpaYLcAbym33g4hsPY/*),a:pkh(tpubDFUyR1hbbP14sGZ2St39RgJ9wUk4enPVYahtA5nPwPPWsGUNVFZt2ujRLShf4JqFXbJQLrgvFTodtXCWEnYQqUnMYzLaAWjuXsZnQTYZS5C/*),a:pkh(tpubDDHWtTfxQzAaYPvXmbVtfbKzkttwHqdE9pYsqcS4rgYxNWk2QAfmBMRkvkHDUBX96L4rw1PYxxgcQQ3rhns6EQdDbiGNi32UVXtwNWE7MsQ/*),a:pkh(tpubDEjfbTUpCPyZ3rUkxFPeScbMJUvijAJxanr5rPUy9Ah2HikqsxbaXSA6kjsXjUEBMe2Q5pKWicXWMUXjau7Am3W1fXHZPbrAMNXa7Z7ygEW/*))))#hrxyuvwx"
cpfp_descriptor = "wsh(thresh(1,pk(tpubDEAoArgp5Xu4jD5KsLuMN88zuh8g3Tzxm3JMG9wNUNGNsAbzBn4bLzHjjQJCtKWy3ZHt5bR7vvBfFpdY59sHaYi9cqXYaJ2sqKnsStzsNLb/*)))#3tw0ayr2"

# The private version of the above keys:
# Stakeholders:
# tprv8gvbCtzoxrJdn3iMgVEkWU6aEQoXK4b6hakmhcy6bEqS46HERndesprPYFi25UGfqmAoqVKY5jiTerovMNbMyzrtwMLQYJEyqN6WL9uuqhG
# tprv8inwGbfMT1KPyoXEZENZ2Ge3NTE8VTCayH76sZk6X7b82nDbrrkHrR7ZALUkdbmE9KPfdEP4MnqmFcgvtBvTLxT5yGJCDPLCmBe9q8c5GRF
# tprv8gbUk3diGcUuevtjswqJGBftBsP18WSKaWx6Z6PmSQkZY2VFmmrAzrotkba8m9sTVSr6mctnhvbdVCwKahjbAwr22K7jvxwX17t4mKZTK1D
# tprv8i3dT3Sa42HtAPSy4bj43CwEjTQnZq841VFJZsSfittdTEW5FZmzLwYEadZFXTMNb2isqkHPMn7nHVRXkUrJdKWf7JWh5C231usN2N8vVNB
# Cosigning servers:
# L1h54b51ky7gPhQi2etvJtiLqCUfWzLthjWjszSmz1S9e9EvvaHd
# KyUa6WXsxax4aqx5ggsDfSTGGc6rW8K1AMmDpoiGLFGPP7Ab4sXZ
# L5EArfK6Rh52DjTDArhDW9pFo5Y7ds8RTcFQ6DrDPRzutk8Hh1tu
# L3GRc9PtTnhqPDuzaafkMTXdKcEzC3fgWgxJwEySojQN5EG3V3jo
# Managers:
# tprv8gEqfDHSqcSuw1eBYp99CirMXSsHNSj8SuHNR3oCqxKBFmMkBtyhrk3hypxG7vqSjyFxtpYeWDUdCQi48C4Q3Dawd1XnJcNuJEre1Haac1m
# tprv8hVKUu8dVE5tz1T1oYe91ne1oCSLu17wXquewi1Ja1ksQKSM1QS8pBfqBJVDQy2B8VoFcGFSWJGFW2rXVsk4WTDqvqa1BFFsVSpFQpKPrjY
# CPFP:
# tprv8hUm2SeZwADPqk3XyhEkxiUtLfcjt8p4BjhZydu546Tz2gMDZPF1AVfsZGHstRGkfbmVg5fwvNhz1cck2e4ji2ySq6ExrNss93i5Xrh6mUV

[bitcoind_config]
network = "regtest"
cookie_path = "/path/to/your/cookie/path/.cookie"
addr = "127.0.0.1:9001"
poll_interval_secs = 3

# This section must be copied only if you're a stakeholder. Put here your xpub, watchtower configuration and Emergency address.
[stakeholder_config]
# This MUST NOT be changed after running revaultd for the first time, or you'll have to re-generate the database.
# If you have to change it, be sure to remove the previous db at `/path/to/your/data_dir/network/revaultd.sqlite3`.
xpub = "tpubDDcdMK347DzJfWk9a8uLuskgoSKTUPn1GtMYz91Q1WdptaY14BTF4KUFiQ3cq5K6ji4bgALTEy6HUuf3TULS4f98wYpaYLcAbym33g4hsPY"
# At the moment this is unused
watchtowers = [ { host = "127.0.0.1:1", noise_key = "46084f8a7da40ef7ffc38efa5af8a33a742b90f920885d17c533bb2a0b680cb3" } ]
emergency_address = "bcrt1qewc2348370pgw8kjz8gy09z8xyh0d9fxde6nzamd3txc9gkmjqmq8m4cdq"

# This section must be copied only if you're a manager. Put here your xpub and cosigning servers configuration.
[manager_config]
# This MUST NOT be changed after running revaultd for the first time, or you'll have to re-generate the database.
# If you have to change it, be sure to remove the previous db at `/path/to/your/data_dir/network/revaultd.sqlite3`.
xpub = "tpubDCvsodKgyz8apUfySTojc8WU6UPDXmv32Ct9hZqWGE7a6FcWpHoJ3Efa9zUqLWHX6PHthHXQehG1mrFtFVXNMcwt6kGwCuYk6adMDreyVGu"
cosigners = [ { host = "127.0.0.1:1", noise_key = "087629614d227ff2b9ed5f2ce2eb7cd527d2d18f866b24009647251fce58de38" } ]
