# If `true`, revaultd will start as a daemon. If you're using revaultd with revault-gui, you might want to keep it to `true`, so that the gui can start revaultd on its own. If you're starting `revaultd` for the first time, you may want to change it to `false`, so that you can see if something goes wrong.
daemon = true
log_level = "debug"
# The directory where all your revault data will be saved
data_dir = "/path/to/your/datadir/revault"

coordinator_host = "127.0.0.1:8383"
coordinator_noise_key = "f35b02f12ff3d64f3c7982b88ffb66fec37bce5796374a7be9e8e2dd9abbb558"

# The specifications of the Bitcoin Script that we are going to be tracking onchain, put here your own that you can
# generate with the `mscompiler` tool (in `contrib/tools`).
# These MUST NOT be changed after running revaultd for the first time, or you'll have to re-generate the database.
# If you have to change it, be sure to remove the previous db at `/path/to/your/data_dir/network/revaultd.sqlite3`.
[scripts_config]
deposit_descriptor = "wsh(multi(4,xpub6DEzq5DNPx2rPiZJ7wvFhxRKUKDoV1GwjFmFdaxFfbsw9HsHyxc9usoRUMxqJaMrwoXh4apahsGEnjAS4cVCBDgqsx5Groww22AdHbgxVDg/*,xpub6F7Ltmsut73cbUNAzh44DkxncMeQfPtRzx7aoXjFbUdd7yofR2intU4b6QcsXot1jgmVjHB3iMybCLhtqvhAx3L4VPbGUz5fwuyNeTkypUP/*,xpub6CutNDrGhiD8GbjgKQWoTfzdRmoHJT8AcBxaV4NvWmo4dE5KKwpg2ukvgiCRwgZuJRXxKRsgRrrZiDZFJw1rLyAvY7X52WNEuaJXcVKLVFG/*,xpub6EN35Df8V826n4HuW4QZEhFyyMq4jmou3AFnVqRpoFw8YS68ojkVNzVGWhnkCyGwZjVVUEoeBWhTfJ38C3Fvsc3ibvYFi5BvmQwAMZkqEqH/*))#yd2wgsza"
unvault_descriptor = "wsh(andor(multi(2,xpub6CZFHPW1GiB8YgV7zGpeQDB6mMHZYPQyUaHrM1nMvKMgLxwok4xCtnzjuxQ3p1LHJUkz5i1Y7bRy5fmGrdg8UBVb39XdXNtWWd2wTsNd7T9/*,xpub6Doj75MBvKp7bgHxF1KeDGxm36rd4wonZWv8sfzTeNoNVX2QZaQdrEcs7NDXvs4Cbsy9TPMx5VDcMK6JjSKepBbYDPiJ9bLBR4bqfdHmxZx/*),and_v(v:multi(4,030f64b922aee2fd597f104bc6cb3b670f1ca2c6c49b1071a1a6c010575d94fe5a,02abe475b199ec3d62fa576faee16a334fdb86ffb26dce75becebaaedf328ac3fe,0314f3dc33595b0d016bb522f6fe3a67680723d842c1b9b8ae6b59fdd8ab5cccb4,025eba3305bd3c829e4e1551aac7358e4178832c739e4fc4729effe428de0398ab),older(18)),thresh(4,pkh(xpub6DEzq5DNPx2rPiZJ7wvFhxRKUKDoV1GwjFmFdaxFfbsw9HsHyxc9usoRUMxqJaMrwoXh4apahsGEnjAS4cVCBDgqsx5Groww22AdHbgxVDg/*),a:pkh(xpub6F7Ltmsut73cbUNAzh44DkxncMeQfPtRzx7aoXjFbUdd7yofR2intU4b6QcsXot1jgmVjHB3iMybCLhtqvhAx3L4VPbGUz5fwuyNeTkypUP/*),a:pkh(xpub6CutNDrGhiD8GbjgKQWoTfzdRmoHJT8AcBxaV4NvWmo4dE5KKwpg2ukvgiCRwgZuJRXxKRsgRrrZiDZFJw1rLyAvY7X52WNEuaJXcVKLVFG/*),a:pkh(xpub6EN35Df8V826n4HuW4QZEhFyyMq4jmou3AFnVqRpoFw8YS68ojkVNzVGWhnkCyGwZjVVUEoeBWhTfJ38C3Fvsc3ibvYFi5BvmQwAMZkqEqH/*))))#8lzssu5l"
cpfp_descriptor = "wsh(thresh(1,pk(xpub6DoAecs8NFwcTQtUR9vGACodaa3245VuDQi3ubtE8TWV7swH7ZDWCYcuVNDRMpZjFekyU1uFPpMcZe8vgJ23h7FrZEnEtmNeFNCTgpPzJ79/*)))#4cxyfeck"

# The private version of the above keys:
# Stakeholders:
# xprv9zFeRZgUZaUZBEUq1vPFLpUavHPK5YZ6N2qeqCYe7GLxGVY9SRHuN5Uwd5YN56tMUKe2qPhmvP8fC1GBEAFRAwbJQi86swWvvGM5tXBpJt6
# xprvA27zVGM23jVKNzHhtfX3rd244KovFwAadjBz19Ke396eFBUWsVQYLfk7FAK6dENumsrtd8mJCSFxnm9BkyaWXuBVSd5tZ2c9r5tjPNkz7A9
# xprv9yvXxiKNsLeq47fDDNyo6Y3tsjxntzQKEy2ygfyJxSG5kRkAnQWRV7SSqRQUknV981KKmXH2Ya1q2MPaTVPeMtaRVfuSGcDU628eKeBU262
# xprvA1Ngfi8EekToZaDSQ2sYsZKFRKzaLK63fwLBhT2DEvQ9fdkzGCSEqCAnfTPbX5y4DbC6qefdCRXypdsndGWMpGF4afJPQqHz6p7wah4q2uG
# Cosigning servers:
# L1h54b51ky7gPhQi2etvJtiLqCUfWzLthjWjszSmz1S9e9EvvaHd
# KyUa6WXsxax4aqx5ggsDfSTGGc6rW8K1AMmDpoiGLFGPP7Ab4sXZ
# L5EArfK6Rh52DjTDArhDW9pFo5Y7ds8RTcFQ6DrDPRzutk8Hh1tu
# L3GRc9PtTnhqPDuzaafkMTXdKcEzC3fgWgxJwEySojQN5EG3V3jo
# Managers:
# xprv9yZtssy7SLcqLCQetFHe35ENDKT58vh87MNFYdNkMyphUAcfCXdxLzgG4enc7ZT8NXjBtivtLrtpjZAJzyiTEAKM6NKUeFerP97DZdctJPr
# xprv9zpNhZpJ5xFpPCDV8yndr922V528fV5wCHzY5Har63GPcihG236PJSJPG8KZQbdrm4GUcAdgLwgT3BJnNfQ7hPxFQCMhWtXpaM4py7XXtpb
# CPFP:
# xprv9zopF7LEXtPKEvp1K8PFo4ru2YCXecn3rBnT7DUca7yWF5c8a1uFekJRe68Dt3tSJAEifz4Bm28BYm4zuRintyhrJT2fC29pDwxf6DBiViY

[bitcoind_config]
network = "regtest"
cookie_path = "/path/to/your/cookie/path/.cookie"
addr = "127.0.0.1:9001"
poll_interval_secs = 3

# This section must be copied only if you're a stakeholder. Put here your xpub, watchtower configuration and Emergency address.
[stakeholder_config]
# This MUST NOT be changed after running revaultd for the first time, or you'll have to re-generate the database.
# If you have to change it, be sure to remove the previous db at `/path/to/your/data_dir/network/revaultd.sqlite3`.
xpub = "xpub6DEzq5DNPx2rPiZJ7wvFhxRKUKDoV1GwjFmFdaxFfbsw9HsHyxc9usoRUMxqJaMrwoXh4apahsGEnjAS4cVCBDgqsx5Groww22AdHbgxVDg"
# At the moment this is unused
watchtowers = [ { host = "127.0.0.1:1", noise_key = "46084f8a7da40ef7ffc38efa5af8a33a742b90f920885d17c533bb2a0b680cb3" } ]
emergency_address = "bcrt1qewc2348370pgw8kjz8gy09z8xyh0d9fxde6nzamd3txc9gkmjqmq8m4cdq"

# This section must be copied only if you're a manager. Put here your xpub and cosigning servers configuration.
[manager_config]
# This MUST NOT be changed after running revaultd for the first time, or you'll have to re-generate the database.
# If you have to change it, be sure to remove the previous db at `/path/to/your/data_dir/network/revaultd.sqlite3`.
xpub = "xpub6CZFHPW1GiB8YgV7zGpeQDB6mMHZYPQyUaHrM1nMvKMgLxwok4xCtnzjuxQ3p1LHJUkz5i1Y7bRy5fmGrdg8UBVb39XdXNtWWd2wTsNd7T9"
cosigners = [ { host = "127.0.0.1:1", noise_key = "087629614d227ff2b9ed5f2ce2eb7cd527d2d18f866b24009647251fce58de38" } ]
