[package]
name = "revaultd"
version = "0.0.1"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[dependencies]
bitcoin = "0.23.0"

toml = "0.5.6"
serde = { version = "1.0.97", features = ["derive"] }

# Don't reinvent the wheel
dirs = "3.0.1"
