[package]
name = "revaultd"
version = "0.0.1"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[dependencies]
revault_tx = { git = "https://github.com/re-vault/revault_tx" }

serde = { version = "1.0", features = ["derive"] }
toml = "0.5.6"

# Don't reinvent the wheel
dirs = "3.0.1"

# It's concise, does the Right Thing, and even supports Windows !
daemonize-simple = "0.1.4"
