unvault_csv = 18

# We can set random values which'll get ignored
wizard = "sardine"

[bitcoind_config]
network = "main"
cookie_path = "/home/user/.bitcoin/.cookie"
addr = "127.0.0.1:8332"

# We are one of the below stakeholders
[ourselves]
stakeholder_xpub = "xpub6AP3nZhB34Zoan3KCL9bAdnwNHdzMbskLudpbchwTfkHwnNDXYf1769gzozjgzDNUF7iwa5nCdhE5byrcx5PDKFCUDByeuqiHa382EKhcay"

	# So is indentation
	[[managers]]
	xpub = "xpub6AtVcKWPpZ9t3Aa3VvzWid1dzJFeXPfNntPbkGsYjNrp7uhXpzSL5QVMCmaHqUzbVUGENEwbBbzF9E8emTxQeP3AzbMjfzvwSDkwUrxg2G4"
	[[managers]]
	xpub = "xpub6AMXQWzNN9GSrWk5SeKdEUK6Ntha87BBtprp95EGSsLiMkUedYcHh53P3J1frsnMqRSssARq6EdRnAJmizJMaBqxCrA3MVGjV7d9wNQAEtm"

[[stakeholders]]
# Even with spaces
    xpub = "xpub6BHATNyFVsBD8MRygTsv2q9WFTJzEB3o6CgJK7sjopcB286bmWFkNYm6kK5fzVe2gk4mJrSK5isFSFommNDST3RYJWSzrAe9V4bEzboHqnA"
cosigner_key = "02644cf9e2b78feb0a751e50502f530a4cbd0bbda3020779605391e71654dd66c2"
[[stakeholders]]
xpub = "xpub6AP3nZhB34Zoan3KCL9bAdnwNHdzMbskLudpbchwTfkHwnNDXYf1769gzozjgzDNUF7iwa5nCdhE5byrcx5PDKFCUDByeuqiHa382EKhcay"
cosigner_key = "03ced55d1208bd8c6b42b11e29baa577711cae831b3a1296607c5e5d3ed365f49c"
[[stakeholders]]
xpub = "xpub6AUkrYoAoySUXnEbspdqL7dJ5qE4n5wTDAXb22tzNaU9cKqpeE6Tjvh5gkXECrX8bGM2Ndgk3HYYVmD7m3NyHxS74NRi1cuq9ddxmhG8RxP"
cosigner_key = "026237f655f3bf45fd6b7aa00e91c2603d6155f1cc001e40f5e47662d965c4c779"
[[stakeholders]]
xpub = "xpub6AL6oiHLkP5bDMry27vH7uethb1g8iTysk5MZJvNe1yBv5fedvqqgiaPS2riWCiu4o3H8xinEVdQ5zz8pZKH1RtjTbdQyxHsMMCBrp2PP8S"
cosigner_key = "030a3cbcfbfdf7122fe7fa830354c956ea6595f2dbde23286f03bc1ec0c1685ca3"
