coordinator_host = "127.0.0.1:1"
coordinator_noise_key = "d91563973102454a7830137e92d0548bc83b4ea2799f1df04622ca1307381402"

[scripts_config]
cpfp_descriptor = "wsh(thresh(1,pk(tpubDC53T8LzVD49ypMBhqVSv56UbFwvt3MNKz3fnPXuN4fovPJCXTC1vgXwwi3ktYFar2nKePCwRESka7RizHGfoCDGmSZTC5sJP8jtgy9qi85/*)))#xwux0ath"
deposit_descriptor = "wsh(multi(2,tpubDEhUqEq2ecZqF6FSJVmJ6sidW346Xn26dHwxfApiyqDLevmFdzsbJBuJY1CAnUN7m2XfUBHaVzUyZsSV4q3xJd3GNEFk9LMezsATooKfbTs/*,tpubDC53T8LzVD4A2ft1JcQkqG4wqrWNMk4aSNwP19qGkevaSNTH6hdBudszRyqGHneczG5oUvfrpdunemtjVSqAd6zRbVLEHLaQgLCnj6aqj5K/*))#c8dyeyw5"
unvault_descriptor = "wsh(andor(thresh(1,pk(tpubDE1nGaGGkCtN1nXgdnQ1phzwhnHvuXREs1K3sRz3PsyDqVVLST5ALkwyY8Ybyb7f3nF5F3L9ep8frKPHZoDtgVYYLjwk9SkS4NmiCAgXq29/*)),and_v(v:multi(2,0332e5c86d0938a83ed80d13c5644ec92fd16b9d7184bb35d6ead8227b4ad47803,02807e5c4f7b228aa9f1aef77effde768356480f5268376644464e714d0205eb1c),older(6)),thresh(2,pkh(tpubDEhUqEq2ecZqF6FSJVmJ6sidW346Xn26dHwxfApiyqDLevmFdzsbJBuJY1CAnUN7m2XfUBHaVzUyZsSV4q3xJd3GNEFk9LMezsATooKfbTs/*),a:pkh(tpubDC53T8LzVD4A2ft1JcQkqG4wqrWNMk4aSNwP19qGkevaSNTH6hdBudszRyqGHneczG5oUvfrpdunemtjVSqAd6zRbVLEHLaQgLCnj6aqj5K/*))))#vtmhr9a2"

[bitcoind_config]
network = "signet"
cookie_path = "/home/user/.bitcoin/signet/.cookie"
addr = "127.0.0.1:8332"


[stakeholder_config]
xpub = "tpubDEhUqEq2ecZqF6FSJVmJ6sidW346Xn26dHwxfApiyqDLevmFdzsbJBuJY1CAnUN7m2XfUBHaVzUyZsSV4q3xJd3GNEFk9LMezsATooKfbTs"
watchtowers = [ { host = "127.0.0.1:1", noise_key = "46084f8a7da40ef7ffc38efa5af8a33a742b90f920885d17c533bb2a0b680cb3" } ]
emergency_address = "tb1qee40l085jthykvuwmkwgu7vf0eu992awna0ktjsngq4jqx5ff3js7d9ndd"
