[package]
name = "mscompiler"
version = "0.0.1"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[dependencies]
revault_tx = { git = "https://github.com/revault/revault_tx" }
serde_json = "1"
