[package]
name = "mscompiler"
version = "0.0.1"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[dependencies]
revault_tx = { git = "https://github.com/danielabrozzoni/revault_tx/", branch = "2021109_support_cpfp", features = ["use-serde"] }
serde_json = "1"
